### ISSUE TITLE
AgentModel leaves around patch objects after resize-world

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Tortoise#117]

**Comment by mrerrormessage** [comment]
As of 7/29/15, this is still occurring: ![screen shot 2015-07-29 at 2 59 40 pm](https://cloud.githubusercontent.com/assets/143198/8968398/7eee00a0-3602-11e5-874e-ec9b1846d8b5.png)

**Comment by TheBizzle** [comment]
Many of the relevant details of this can actually be found in NetLogo/Galapagos#160.

**Comment by qiemem** [comment]
This appears to be a dup of #115, though I opened them a day apart...
