### ISSUE TITLE
`run` and `run-result` are very incomplete

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Tortoise#122]
This has been a known issue for a while now, but I'm opening a ticket to document it.

Our current implementations of `run` and `run-result` are very... primitive—you may hold your applause.  They do not work when provided with strings (rather than tasks).  This prevents the following compiling models from running correctly:
- Code Examples/Breed Procedures Example
- Curricular Models/BEAGLE Evolution/Bird Breeder
- Sample Models/Computer Science/Artificial Neural Net - Multilayer
- Sample Models/Computer Science/Artificial Neural Net - Perceptron
- Sample Models/Mathematics/Fractals/L-System Fractals

Fixing this problem requires getting the compiler into the browser.

**Comment by mrerrormessage** [comment]
Has there been any decision on this? Given that we're one PR away from having the Compiler in Javascript, it seems attainable to have `run`/`runresult` on strings, but is that desirable? Is it possible to rewrite any/all of the above models to use tasks instead of strings? Perhaps some of our models folks can weigh in here - @arthurhjorth ? @qiemem ?

**Comment by qiemem** [comment]
> Is it possible to rewrite any/all of the above models to use tasks instead of strings?

I wish. For instance, `apply` cannot be done with just tasks: NetLogo/NetLogo#539

Anything requiring variadic-ish anonymous functions must be done with strings. The general solution to NetLogo/NetLogo#771 (something like `?*`, or javascript's `arguments`) would remove this need I think.

Macro-like things still have to be done with strings, but I can't think of places I've wanted that except for the variadic thing.

**Comment by ToonTalk** [comment]
As runresult of strings isn't (yet) supported perhaps an appropriate error message could be generated instead of "world.observer.getGlobal(...) is not a function"

**Comment by TheBizzle** [comment]
@ToonTalk, you're right that that change was far overdue.  I rolled out a patch to netlogoweb.org so that calling `run`/`run-result` with a string argument will give you a much more explicit error message about what went wrong (a la 497abfb8f3d3fe9cb7a4f906eb915a72ebd2be52)

**Comment by LaCuneta** [comment]
Support for `run` and `run-result` on strings has been added and deployed.
