### ISSUE TITLE
Token error when "\"" in code

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#132]
The following works fine in NetLogo

to test
  ask patch 0 0 [set plabel-color white set plabel "\""]
end

but after using http://li425-91.members.linode.com:9000/create-standalone the JavaScript console says:

Uncaught SyntaxError: Unexpected token ILLEGAL

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Galapagos#223
