### ISSUE TITLE
hsb undefined but not directly called

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#142]
Today I'm getting

unknown primitive: org.nlogo.core.prim.etc._hsb

from http://736-dot-m4a-gae-hrd.appspot.com/p/WQwz60uMxlGoAFDPykyM7b.nlogo

while it worked yesterday.

And the model doesn't directly call HSB.

**Comment by TheBizzle** [comment]
It does call `hsb`.  The line `report hsb hue 255 255` is present at the end of the `log-as-hue` reporter.

**Comment by ToonTalk** [comment]
Sorry I was working on two models at once and searched for hsb in the wrong one.
