### ISSUE TITLE
Compile button causes shape variable to be ignored

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#145]
This

http://li425-91.members.linode.com:9000/tortoise#http://m.modelling4all.org/p/XYJojeyWVuFczEu7xcVr7h.nlogo

displays fine after setup. If I then click on the NetLogo Code button and then the compile button the model displays only the default turtle shape (even though the turtles shape variable is still wolf and sheep).

**Comment by TheBizzle** [comment]
Moved to NetLogo/Galapagos#237
