### ISSUE TITLE
Setup takes 30 seconds - compared with less than 1 second in JVM version

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#147]
This isn't my model and it is complex but wondering if there is anything that can be done about its very long setup time.

http://li425-91.members.linode.com:9000/create-standalone#http://751.m4a-gae-hrd.appspot.com/p/EzTuAKReYQK6eM5yucZ87c.nlogo

**Comment by ToonTalk** [comment]
I suspect it is the plots and/or plot pens.

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Galapagos#246
