### ISSUE TITLE
Error when asking an initially-empty-but-now-filled special agentset

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Tortoise#152]
Here's the simplified code that causes the error:

```
breed [apples apple]

to setup
  ca
  let xs apples
  create-apples 2 ; Shufflerator won't shuffle unless there are at least two items 
  ask xs [ set size 10 ]
end
```

When the `ask` is run, an error will be printed in the JS console, and the turtles' sizes will **not** be adjusted.

The problem is...—well, debatable.  I might argue that the problem is the existence of special agentsets, but that won't accomplish too much at the moment.  The _line of code_ that creates the problem is [this one](https://github.com/NetLogo/Tortoise/blob/6f41b08037b17227d8a4dd60a23a3893a5e1f945/jvm/src/main/coffee/engine/core/abstractagentset.coffee#L22).

This error was initially discovered by trying to run my Bladder Patrol model through the converter, so all you haters are gonna have to just deal with the fact that it's still the greatest, most useful model around!  You can't deny it anymore.

**Comment by SethTisue** [comment]
re: the debatableness of special agentsets, see NetLogo/NetLogo#501
