### ISSUE TITLE
Error running in an iframe in IE11

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#156]
When I click on 'Play Game' after this loads: http://m.modelling4all.org/m/?EGM=1

It breaks on

  now = (_ref = typeof performance !== "undefined" && performance !== null ? performance.now.bind(performance) : void 0) != null ? _ref : Date.now.bind(Date);

where performance is defined but performance.now isn't. performance.timing is defined -- perhaps that is what IE calls it?

Works fine in Chrome and FireFox.

I tried to isolate this and discovered that without an iframe it works in IE11 and in some other circumstances it runs in an iframe OK

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Galapagos#252
