### ISSUE TITLE
Plots and Monitors with invalid code cause errors

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/Tortoise#160]
See code [in this gist](https://gist.githubusercontent.com/mrerrormessage/80f67e1c6f53ef123202/raw/e560812bceb3543254d32b0adf31dbe37ebdbccd/Unimplemented%2520Prim%2520Widgets.nlogo).

When plots have unimplemented code in their setup or update functions, the Tortoise compiler emits code like:
```javascript
//...
modelConfig.plots = [modelConfig.output.write("Errors in plot vars initialization unknown primitive: org.nlogo.core.prim.etc._dateandtime");];
//...
```
This isn't even valid javascript, and will cause world initialization to break.

When monitors have errant code, they emit an error data structure instead of a string that can be turned into a function. The `success` of the result needs to be checked before turning it into a Function. [See here in Galapagos](https://github.com/NetLogo/Galapagos/blob/master/app/assets/javascripts/TortoiseJS/agent/widgets.coffee#L173-L174).

@TheBizzle also reports that
> If you have a button that involves an unimplemented primitive, and then another that simply has invalid code, and you click the one with the invalid code, you are told about the unimplemented primitive in the button you didn't click

This is not reproduced in the attached model.

This may also require a fix in Galapagos.

**Comment by TheBizzle** [comment]
I feel that the crux of this problem is that [`WidgetCompiler`](https://github.com/NetLogo/Tortoise/blob/0aff5c0765f2c63789d849c5213aa60cce7eeaa0/tortoise/src/main/scala/WidgetCompiler.scala#L65-L81) does not distinguish between widgets that passed compilation and widgets that did not.

**Comment by TheBizzle** [comment]
Superseded by #165.
