### ISSUE TITLE
`set-default-shape` support

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/Tortoise#161]
Per https://github.com/NetLogo/Galapagos/pull/211, one of the test models uses `set-default-shape` and the button that uses it is broken.

**Comment by TheBizzle** [comment]
Which one?

**Comment by TheBizzle** [comment]
Note that it can't be the case that `set-default-shape` is entirely broken, because WSP uses it for setting wolf and sheep shapes, and they show up just fine.

**Comment by TheBizzle** [comment]
Looks to me like the "change-default-shape" button in the "Shapes and Link Shapes" test model fails to work because the button's code doesn't compile.

**Comment by TheBizzle** [comment]
Or, rather, there seems to be an error coming from one of the other widgets in the model.  Either way, the problem isn't with `set-default-shape`.  Closing as "invalid".

**Comment by mrerrormessage** [comment]
Sorry, should have checked more thoroughly. It is the `shapes` primitive that is missing. Shall I open a new ticket for that, or reopen and change this one to reflect?

**Comment by TheBizzle** [comment]
#119 is already the catch-all issue for missing primitives.
