### ISSUE TITLE
an agent that reports `false` can be return by `min-one-of`

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Tortoise#166]
Instead, such agents should be removed as potential candidates.

To reproduce, run the following in desktop NetLogo and NLW (the 

```
crt 100
show [min-one-of turtles [ ifelse-value true [ false ] [ false ] ]] of turtle 0
```

This breaks the DLA Alternate models.

**Comment by qiemem** [comment]
The `ifelse-value` trickier is necessary for the NetLogo compiler to accept the expression.

**Comment by SethTisue** [comment]
or just `crt 1 let x false show min-one-of turtles [x]`
