### ISSUE TITLE
http://www.netlogoweb.org/launch#... reports an error while http://li425-91.members.linode.com:9000/create-standalone# works

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#169]
This URL works:

http://li425-91.members.linode.com:9000/create-standalone#http://762-dot-m4a-gae-hrd.appspot.com/p/ETED3KRLHrhRtiz2JNf26e.nlogo

While this one doesn't: 

http://www.netlogoweb.org/launch#http://762-dot-m4a-gae-hrd.appspot.com/p/ETED3KRLHrhRtiz2JNf26e.nlogo

It generates the message "Models must have 12 sections, this had 1".

http://www.netlogoweb.org/launch works fine if I click on the 'Choose file' button

**Comment by mrerrormessage** [comment]
Doing a quick `curl -v` shows this:
```
* Connected to 762-dot-m4a-gae-hrd.appspot.com (173.194.197.141) port 80 (#0)
> GET /p/ETED3KRLHrhRtiz2JNf26e.nlogo HTTP/1.1
> Host: 762-dot-m4a-gae-hrd.appspot.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/force-download; charset=UTF-8
< Date: Mon, 17 Aug 2015 14:47:46 GMT
< Transfer-Encoding: chunked
< Server: Google Frontend
<
```

I'll do a little digging, but my first suspicion is that it ajax requests may not play nice with "application/force-download".

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Galapagos#309
