### ISSUE TITLE
A graph causes a model to crawl

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#177]
This model slows down drastically after a dozen ticks:

https://dl.dropboxusercontent.com/u/51973316/Temp/spiral-of-silence.html

while this version (identical except a simple graph removed) runs fine:

https://dl.dropboxusercontent.com/u/51973316/Temp/spiral-of-silence-good.html

Both run fine in 5.3.1

**Comment by TheBizzle** [comment]
I'm looking into this.  Somehow, `plotting-commands` is coming to have over a hundred thousand entries (vs. having just one 4-item list in desktop NetLogo).  Pretty sure this is a bug on our end, but I'm not yet sure exactly what's going on.  I'll get back to you with more info (and very probably a bugfix) in the coming days.

**Comment by TheBizzle** [comment]
The fix for this is now available on https://netlogoweb.org/launch .
