### ISSUE TITLE
Dropbox comment in http://www.netlogoweb.org/info no longer true

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#178]
Like any other HTML file, files generated in this way can then be hosted on a web server (including on a file-serving service like Dropbox) and viewed in any modern browser.

Dropbox no longer offers this service to free accounts created after 2012. https://www.dropbox.com/help/16

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Galapagos#332
