### ISSUE TITLE
`hatch-<breed>` should initialize new `<breeds>-own` variables to 0

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Tortoise#186]
Dor Abrahamson writes:

> http://www.netlogoweb.org/launch#http://www.netlogoweb.org/assets/modelslib/Curricular%20Models/ProbLab/4%20Block%20Stalagmites.nlogo
> 
> Setup
> Go
> Organize
>
> “Error
> Checking equality on undefined is an invalid condition”

The problem stems from the fact that `hatch-sample-organizers` is being called by `sample-dudes`, while  `sample-organizers` have the variable `original-pycor`, but `sample-dudes` do not.  `original-pycor` is being initialized to `undefined`, rather than `0`.  The malfeasant line is [here](https://github.com/NetLogo/Tortoise/blob/master/jvm/src/main/coffee/engine/core/turtle.coffee#L314), where no effort is made to do anything sensible if the new variable didn't actually exist in the old hatcher's breed.

Fix incoming shortly.

**Comment by SethTisue** [comment]
is there missing test coverage for this back in the main NetLogo repo?

**Comment by TheBizzle** [comment]
There was.  [I've added a test for it now.](https://github.com/NetLogo/NetLogo/commit/b0ffc9400c9402d4cd93b49b1c4f01973d5b0b9b)

**Comment by TheBizzle** [comment]
Fixed by d0f8377.
