### ISSUE TITLE
Client-side compilation

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Tortoise#19]
Once the refactoring is complete and jflex is removed, compilation to js with scalajs should be possible.

**Comment by TheBizzle** [comment]
@mrerrormessage is currently working on this on the [`wip-javascript-compiler`](https://github.com/NetLogo/Tortoise/tree/wip-javascript-compiler) branch.

**Comment by mrerrormessage** [comment]
Closed by https://github.com/NetLogo/Tortoise/pull/129.

**Comment by SethTisue** [comment]
:tada:
