### ISSUE TITLE
arrows too big

### ISSUE THREAD

**Issue by digitaldust** [NetLogo/Tortoise#199]
I have exported my model to Netlogo Web but when I open the html file, it looks like the arrows in my links are way too big.
![schermata 2018-03-16 alle 15 07 49](https://user-images.githubusercontent.com/3994257/37525029-f3396d68-292b-11e8-84fd-b8333dd75624.png)

**Comment by LaCuneta** [comment]
Hey @digitaldust, thanks for reporting.  This issue has already been reported over in the [Galapagos repository](https://github.com/NetLogo/Galapagos/issues/298), so I'm closing it here.
