### ISSUE TITLE
Is is possible to remove the DOM dependency?

### ISSUE THREAD

**Issue by CIVITAS-John** [NetLogo/Tortoise#207]
Dear All,
Thanks for your last response and I am now able to compile & run it in browsers. However, as the engine.js currently depends on DOM components (like the window), it cannot run in V8 and has to embed within a CEF (Chrome Embedded Framework). While to remove the DOM dependency may solve it, I wonder if this is possible?

**Comment by CIVITAS-John** [comment]
UPDATE: Part of the problem has been solved. I am not familiar with Scala.js, but I know it works with node.js... In fact, other code in engine.js also calls `window`, but I can use a dummy `window = {}` to solve it.

**Comment by TheBizzle** [comment]
Hi, John.  Since I only want to use the GitHub issue-tracker for bug reports and feature requests, I'm going to close this ticket.  I sent a reply to the contents of this ticket [on netlogo-devel](https://groups.google.com/forum/#!topic/netlogo-devel/GxZJS9pDgqY).
