### ISSUE TITLE
Different behavior between Desktop and Web: carefully

### ISSUE THREAD

**Issue by CIVITAS-John** [NetLogo/Tortoise#215]
Hi all,

I encountered another discrepancy between desktop and web NetLogo again. The following code aims to sprout a given number (initial-residents) on an agent set. First, all patches in the set will be filled with at least one resident; second, if there are no patches matching this condition (the second block of carefully), the resident will be sprouted in a random patch matching another condition.

However, while on NetLogo Desktop it successfully gives me the correct number of residents, on Web it only sprouts the first resident in households. I am testing more to figure out the source of this.

Best,
John Chen

```netlogo
  repeat initial-residents [
    carefully [
      ask one-of houses with [
        (length owners) < min-residents-per-household
      ] [ sprout-resident ]
    ] [
      ask one-of houses with [
        (length owners) < max-residents-per-household
      ] [ sprout-resident ]
    ]
  ]
```

**Comment by CIVITAS-John** [comment]
I looked into the generated Javascript code, which states:

```javascript
        try {
          world.observer.getGlobal("houses")._optimalOneOfWith(function() {
            return Prims.lt(ListPrims.length(SelfManager.self().getPatchVariable("owners")), world.observer.getGlobal("min-residents-per-household"));
          }).ask(function() { procedures["SPROUT-RESIDENT"](); }, true);
        } catch (_error_8113_8122) {
          world.observer.getGlobal("houses")._optimalOneOfWith(function() {
            return Prims.lt(ListPrims.length(SelfManager.self().getPatchVariable("owners")), world.observer.getGlobal("max-residents-per-household"));
          }).ask(function() { procedures["SPROUT-RESIDENT"](); }, true);
        }
```

Could it because of the different way that _optimalOneOfWith implements?

**Comment by CIVITAS-John** [comment]
It works when I change the code to:

```netlogo
    let candidate one-of houses with [ (length owners) < min-residents-per-household ]
    if (candidate = nobody) [ set candidate one-of houses with 
      [ (length owners) < max-residents-per-household ] ]
    ask candidate [ sprout-resident ]
```

Yes, my previous way of implementation is hacky. However, the underlying bug might need to resolve nevertheless..

**Comment by LaCuneta** [comment]
Thanks for raising the issue and for the research.  It does appears to be the problem is that the `_optimalOneOfWith()` does not raise an exception when no item is found.  A more minimal reproduction, the below throws an error in desktop but runs without a problem in web:

```
  clear-all
  ask one-of patches with [pcolor = blue] [set pcolor red]
```

**Comment by LaCuneta** [comment]
So this is actually I little trickier than I thought at first glance.  The [docs for `one-of`](https://ccl.northwestern.edu/netlogo/docs/dictionary.html#one-of) state that with an empty agentset it returns `Nobody` but with an empty list it throws an error.  So the problem with the example above is with `ask` not throwing the error when used with `Nobody`, not `one-of` or `_optimalOneOfWith`.  However, `one-of` in Netlogo Web doesn't throw the error when given an empty list, so it does still have a problem.

```
```

**Comment by CIVITAS-John** [comment]
Hi Jeremy,

Thanks for the response! I wonder if there are any differences between an
agentset and a list of agents - are there any performance implications?

Best,
John Chen

Jeremy B <notifications@github.com> 于2020年6月22日周一 下午2:29写道：
