### ISSUE TITLE
compiler: agent-type checking isn't occurring

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Tortoise#23]
so e.g. `crt 1 [ crt 1 ]` flies right past the compiler

noticed by @qiemem

**Comment by TheBizzle** [comment]
#27 is now closed, so I think this can now be addressed whenever someone feels up to it.

**Comment by mrerrormessage** [comment]
This has been resolved by updating NetLogo-Headless and can be verified on Linode by running `crt 1 [ crt 1 ]` in the command center.

**Comment by SethTisue** [comment]
:tada:
