### ISSUE TITLE
Encode Encore: bytes-to-base64 not working when the input is too large

### ISSUE THREAD

**Issue by CIVITAS-John** [NetLogo/Tortoise#233]
Please refer to the second answer: the current way to implement the function is 

`btoa(String.fromCharCode(bytes...))`

However, when the length of bytes gets too large, it will exceed the call stack limit. Therefore, seems that the first answer provides a better way to implement, and we could fix this issue very easily.

**Comment by CIVITAS-John** [comment]
Also, I am not sure if the functional style in this extension could bring up the best performance. We don't need to call a function for each byte.

**Comment by CIVITAS-John** [comment]
A very quick change in the compiled js file:

```javascript
 for (var x of bytes) {
  if (!(checks.isNumber(x) && (x >= 0) && (x <= 255)))
    throw exceptions.extension(`All elements of the list argument to 'encode:${primName}' must be numbers between 0 and 255`);
}
return f(bytes);
```

**Comment by TheBizzle** [comment]
What are the "first answer" and "second answer" that you're referring to?

**Comment by CIVITAS-John** [comment]
This is how we implemented:
![image](https://user-images.githubusercontent.com/12299703/162491689-54733eaf-f716-4539-8eac-36246ba7fcdc.png)

This is the better (and uglier) way:
![image](https://user-images.githubusercontent.com/12299703/162491669-00abeffb-499a-4241-adf4-b1206d299da5.png)

**Comment by TheBizzle** [comment]
I have not been able to reproduce this issue with either a 40MB string passed to `base64-to-bytes`, nor with a 100MB string passed to `string-to-bytes`.

Please include in your report

  * What primitive you called
  * What arguments you called that primitive with (as an attached file, if necessary)
  * And what error you received

**Comment by CIVITAS-John** [comment]
Hi, the primitive you need to test is `bytes-to-base64`, not vice versa. 

Please also consider changing the verification to a simple loop (instead of nested functions).

**Comment by CIVITAS-John** [comment]
The easiest way is just to convert your 40MB string to bytes and back to base64.
