### ISSUE TITLE
Primitives with optional arguments do not work well with `apply-result`.

### ISSUE THREAD

**Issue by CIVITAS-John** [NetLogo/Tortoise#242]
Submitted by @Maizi. https://gitee.com/turtle-sim/turtle-universe-issue-tracker/issues/I59OEO

To reproduce, try `__apply-result word ["str1""str2""str3"]`.

Expected: `str1str2str3`.
Actual: `str1str2`.

The reason is that at compilation time, __apply-result would assume only 2 parameters for `word`.

**Comment by LaCuneta** [comment]
:+1: Thanks for the report.  I happen to be working on variadic-args parity with desktop at the moment, so I'll throw this test case into the mix.

**Comment by LaCuneta** [comment]
Resolved in [this commit](https://github.com/NetLogo/Tortoise/commit/d82886852ee964ac11a3f6742dd87eac32ffd557), and test case added to NetLogo [here](https://github.com/NetLogo/NetLogo/commit/9b02e7bacfca33444e0ac9e62e12bba24c56f1ee).
