### ISSUE TITLE
`Error: java is not defined` when using `random-normal command` in NL Web

### ISSUE THREAD

**Issue by wolfj95** [NetLogo/Tortoise#244]
Hello!

I'm getting this error message when using the `random-normal` command in NetLogo Web:
```
Error: java is not defined
```

I am trying to use the `random-normal` command in a full model, but I've isolated the issue to this command using this very simplified model:
```
to setup
  print random-normal 100 5
end
```

This command is working fine in my model on NL Desktop.

Here is my system the information from NL Desktop:
NetLogo 6.2.2 (December 8, 2021)
Extension API version: 6.1
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.15
Java heap: used = 22 MB, free = 237 MB, max = 910 MB

Additionally, I'm running into this issue on NL Web using the following version of chrome:
Version 103.0.5060.134 (Official Build) (x86_64)

**Comment by LaCuneta** [comment]
Thanks for the report!  And sorry you ran into this problem.  This is actually an issue with the Tortoise engine that Galapagos uses (I know it's confusing), so I've transferred it over.  I'll let you know what I find.

**Comment by LaCuneta** [comment]
I've got a fix for this [here](https://github.com/NetLogo/Tortoise/commit/a7fc52f13d475ee6a0d52c63f3913abe0d9f71d8), and because this is broken on netlogoweb.org, I'll try to push out an update with that fix later today.  Thanks again for your report!
